name: 'Validate Version'
description: 'Validate version'
outputs:
  imageTag: 
    description: "Image TAG"
    value: ${{ steps.validate_pr.outputs.image-tag }}
  versionCandidate:
    description: "New Semantic Version"
    value: ${{ steps.validate_pr.outputs.new-version }}
runs:
  using: "composite"
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Validate pull request name
      id: validate_pr
      env:
        release_name: ${{ github.event.pull_request.title }}
      shell: bash
      run: |
        check_package_version=$(git tag --list --sort=-version:refname | head -n 1)
        echo "Checker: $check_package_version"
        if [ $check_package_version = "staging" ]; then 
          package_version=$(git tag --list --sort=-version:refname | sed -n 2p) 
        else
          package_version=$(git tag --list --sort=-version:refname | head -n 1)
        fi
        echo "Verificando se existe tag"
        if [ "$package_version" = "" ]; then
          package_version=0.0.1
        fi
        echo "Nome da release: $release_name"
        new_version_name=$(echo $release_name | grep -oP "((M|m){1}ajor)|((M|m){1}inor)|((P|p){1}atch)" | tr '[:upper:]' '[:lower:]')
        echo "Old version: $package_version"
        echo "Type of version: $new_version_name"
        if [ ! -z "$new_version_name" ]; then
          VERSION=$package_version
          # Divida a versão em partes
          IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"
          
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          
          # Verifique qual parte incrementar
          case "$new_version_name" in
            patch)
              PATCH=$((PATCH + 1))
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            *)
              echo "Tipo desconhecido: $1"
              exit 1
              ;;
          esac
          
          # Monte a nova versão
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          
          # Atualize o arquivo de versão ou crie um novo commit
          echo "$NEW_VERSION" > VERSION
          echo "New version: $NEW_VERSION"
          new_version=$NEW_VERSION
          branch_name=${{ github.head_ref }}
          image_tag=$(echo $branch_name | sed 's/\//_/g')
          echo "image-tag=$image_tag" >> $GITHUB_OUTPUT
          echo "new-version=$new_version" >> $GITHUB_OUTPUT
        else
            echo "Título do pull request deve finalizar com (Major), (Minor) ou (Patch)" >&2
            exit 1
        fi
